image: maven:3.6.3-openjdk-11-slim

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
    
stages:
  - check syntax
  - test and grade
  - test 
 
build:
  stage: check syntax
  script:
    - mvn compile


test:
  stage: test and grade
  script:
    - mvn test
    
grade:
  stage: test and grade
  script: 
    - mvn clean pmd:pmd test checkstyle:checkstyle spotbugs:spotbugs exec:java -Dmaven.test.failure.ignore=true
  artifacts:
    paths:
    - target/grading.md
    reports:
      junit: target/surefire-reports/*.xml